AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Description: WebSocket

Globals:
  Function:
    Tracing: Active
    Architectures:
      - arm64
    Runtime: nodejs20.x
    PropagateTags: true
    Environment:
      Variables:
        GIT_COMMIT: !Ref GITCommit

Parameters:
  Stack:
    Type: String
  Stage:
    Type: String
  LogRetentionInDays:
    Type: String
  GITCommit:
    Type: String
  DynamoDBStackTableName:
    Type: String
  ApiGatewayWebSocketId:
    Type: String
  WebSocketAuthFunction:
    Type: String
  SNSAlarmTopic:
    Type: String

Metadata:
  expand:
    plugins:
      - '../git.mjs'
      - '../hash.mjs'
      - '@starterstack/sam-expand/plugins/parameter-overrides'
      - '../stack-stage-config.mjs'
      - '@starterstack/sam-expand/plugins/run-script-hooks'
      - '../purge-lambda-versions.mjs'
      - '../generate-cloudwatch-alarms.mjs'

    config:
      stackStageConfig:
        suffixStage: true
        addMappings: true
      parameterOverrides:
        - location: ../stack-stage-config.mjs
          overrides:
            - name: SNSAlarmTopic
              exportName: snsAlarmTopic
            - name: Stage
              exportName: stage
            - name: LogRetentionInDays
              exportName: logRetentionInDays
            - name: DynamoDBStackTableName
              exportName: dynamodbStackTableName
            - name: ApiGatewayWebSocketId
              exportName: apiGatewayWebSocketId
            - name: WebSocketAuthFunction
              exportName: websocketAuthFunction
        - location: ../git.mjs
          overrides:
            - name: GITCommit
              exportName: commit
      purgeLambdaVersions:
        keep: 3
      script:
        hooks:
          post:deploy:
            - command: ../tag-eventbus-rules.sh
              args:
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stackName
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: region
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stage
            - command: ../tag-cloudwatch-alarms.sh
              args:
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stackName
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: region
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stage
      alarms:
        snsTopicRef: SNSAlarmTopic

Resources:
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}
      RetentionInDays: !Ref LogRetentionInDays
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName} lambda logs'
        - Key: 'ManagedBy'
          Value: !Ref Stack

  ConnectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/connections/
      Handler: index.handler
      Description: 'websocket connections'
      Timeout: 6
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBStackTableName
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: CloudWatchLogGroup
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt CloudWatchLogGroup.Arn
              Effect: Allow
        - Version: 2012-10-17
          Statement:
            - Sid: ApiGateway
              Action:
                - execute-api:ManageConnections
              Resource:
                - !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayWebSocketId}/${Stage}/POST/@connections/*'
                - !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayWebSocketId}/${Stage}/DELETE/@connections/*'
              Effect: Allow
            - Sid: DynamoDBItem
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:Query
              Resource:
                - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBStackTableName}
              Condition:
                ForAllValues:StringLike:
                  dynamodb:LeadingKeys:
                    - 'graphql-ws-connection#*'
              Effect: Allow
            - Sid: DynamoDBBatchWrite
              Action:
                - dynamodb:BatchWriteItem
              Resource:
                - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBStackTableName}
              Effect: Allow
              Condition:
                ForAllValues:StringLike:
                  dynamodb:LeadingKeys:
                    - 'graphql-ws-subscription#id#*'
      LoggingConfig:
        LogGroup: !Ref CloudWatchLogGroup
    Metadata:
      BuildMethod: makefile

    ConnectionsFunctionPermissionWebSockets:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt ConnectionsFunction.Arn
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com

    ConnectionsFunctionIntegrationWebSockets:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ApiGatewayWebSocketId
        IntegrationType: AWS_PROXY
        IntegrationUri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectionsFunction.Arn}/invocations'

    ConnectionsFunctionAuthWebSockets:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        ApiId: !Ref ApiGatewayWebSocketId
        Name: ConnectionsFunctionWebSocketAuth
        AuthorizerType: REQUEST
        AuthorizerUri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketAuthFunction}/invocations'
        IdentitySource:
          - route.request.header.cookie

    ConnectionsFunctionConnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ApiGatewayWebSocketId
        RouteKey: $connect
        AuthorizationType: CUSTOM
        AuthorizerId: !Ref ConnectionsFunctionAuthWebSockets
        Target: !Sub integrations/${ConnectionsFunctionIntegrationWebSockets}

    ConnectionsFunctionDisconnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ApiGatewayWebSocketId
        RouteKey: $disconnect
        Target: !Sub integrations/${ConnectionsFunctionIntegrationWebSockets}

    ConnectionsFunctionConnectionInitRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ApiGatewayWebSocketId
        RouteKey: connection_init
        Target: !Sub integrations/${ConnectionsFunctionIntegrationWebSockets}

    ConnectionsFunctionPingRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ApiGatewayWebSocketId
        RouteKey: ping
        Target: !Sub integrations/${ConnectionsFunctionIntegrationWebSockets}
