AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Description: Stack Audit

Globals:
  Function:
    Tracing: Active
    Architectures:
      - arm64
    Runtime: nodejs20.x
    PropagateTags: true
    Environment:
      Variables:
        GIT_COMMIT: !Ref GITCommit

Parameters:
  Stack:
    Type: String
  Stage:
    Type: String
  LogRetentionInDays:
    Type: String
  GITCommit:
    Type: String
  EventBusArn:
    Type: String
  DynamoDBStackTableStreamArn:
    Type: String
  DynamoDBStackAuditTableName:
    Type: String
  SNSAlarmTopic:
    Type: String

Metadata:
  expand:
    plugins:
      - '../git.mjs'
      - '../hash.mjs'
      - '@starterstack/sam-expand/plugins/parameter-overrides'
      - '../stack-stage-config.mjs'
      - '@starterstack/sam-expand/plugins/run-script-hooks'
      - '../purge-lambda-versions.mjs'
      - '../generate-cloudwatch-alarms.mjs'

    config:
      stackStageConfig:
        suffixStage: true
        addMappings: true
      parameterOverrides:
        - location: ../stack-stage-config.mjs
          overrides:
            - name: SNSAlarmTopic
              exportName: snsAlarmTopic
            - name: Stage
              exportName: stage
            - name: LogRetentionInDays
              exportName: logRetentionInDays
            - name: EventBusArn
              exportName: eventBusArn
            - name: DynamoDBStackTableStreamArn
              exportName: dynamodbStackTableStreamArn
            - name: DynamoDBStackAuditTableName
              exportName: dynamodbStackAuditTableName
        - location: ../git.mjs
          overrides:
            - name: GITCommit
              exportName: commit
      purgeLambdaVersions:
        keep: 3
      script:
        hooks:
          post:deploy:
            - command: ../tag-eventbus-rules.sh
              args:
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stackName
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: region
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stage
            - command: ../tag-cloudwatch-alarms.sh
              args:
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stackName
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: region
                - file:
                    location: ../stack-stage-config.mjs
                    exportName: stage
      alarms:
        snsTopicRef: SNSAlarmTopic

Resources:
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}
      RetentionInDays: !Ref LogRetentionInDays
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName} lambda logs'
        - Key: 'ManagedBy'
          Value: !Ref Stack
  EventsDlq:
    Type: AWS::SQS::Queue
    Properties:
      SqsManagedSseEnabled: true
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-events-dlq'
        - Key: 'ManagedBy'
          Value: !Ref Stack
  EventsDlqPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'sqs:SendMessage'
            Principal:
              Service: 'events.amazonaws.com'
            Resource: !GetAtt EventsDlq.Arn
            Condition:
              ArnEquals:
                'aws:SourceArn': !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/${AWS::StackName}*'
          - Effect: Allow
            Action:
              - 'sqs:SendMessage'
            Principal:
              Service: 'sns.amazonaws.com'
            Resource: !GetAtt EventsDlq.Arn
            Condition:
              ArnEquals:
                'aws:SourceArn': !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}*'
      Queues:
        - !Ref EventsDlq
  LambdaDlq:
    Type: AWS::SQS::Queue
    Properties:
      SqsManagedSseEnabled: true
      Tags:
        - Key: 'Name'
          Value: !Sub ${AWS::StackName}-lambda-dlq
        - Key: 'ManagedBy'
          Value: !Ref Stack
  PipeDynamoDBToEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - pipes.amazonaws.com
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-pipe-dynamodb-to-eventbridge-dlq-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt PipesDlq.Arn
        - PolicyName: !Sub '${AWS::StackName}-pipe-dynamodb-to-eventbridge-source-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !Ref DynamoDBStackTableStreamArn
        - PolicyName: !Sub '${AWS::StackName}-pipe-dynamodb-to-eventbridge-target-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - !Ref EventBusArn
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-pipe-dynamodb-to-eventbridge-role'
        - Key: 'ManagedBy'
          Value: !Ref Stack
  PipeDynamoDBToAuditRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - pipes.amazonaws.com
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-pipe-dynamodb-to-audit-dlq-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt PipesDlq.Arn
        - PolicyName: !Sub '${AWS::StackName}-pipe-dynamodb-to-audit-source-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !Ref DynamoDBStackTableStreamArn
        - PolicyName: !Sub '${AWS::StackName}-pipe-dynamodb-to-audit-target-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt AuditFunction.Arn
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-pipe-dynamodb-to-audit-role'
        - Key: 'ManagedBy'
          Value: !Ref Stack
  PipeAudit:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !GetAtt PipeDynamoDBToAuditRole.Arn
      Source: !Ref DynamoDBStackTableStreamArn
      Description: 'Pipe to connect stack table stream changes to audit lambda'
      SourceParameters:
        DynamoDBStreamParameters:
          BatchSize: 10
          DeadLetterConfig:
            Arn: !GetAtt PipesDlq.Arn
          OnPartialBatchItemFailure: AUTOMATIC_BISECT
          StartingPosition: LATEST
          MaximumBatchingWindowInSeconds: 1
      Target: !GetAtt AuditFunction.Arn
      TargetParameters:
        LambdaFunctionParameters:
          InvocationType: 'REQUEST_RESPONSE'

      Tags:
        Name: !Sub ${AWS::StackName}-pipe-audit
        ManagedBy: !Ref Stage
  PipesDlq:
    Type: AWS::SQS::Queue
    Properties:
      SqsManagedSseEnabled: true
      Tags:
        - Key: 'Name'
          Value: !Sub ${AWS::StackName}-pipes-dlq
        - Key: 'ManagedBy'
          Value: !Ref Stack

  AuditFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/audit/
      Handler: index.handler
      Description: 'audit data in stack table'
      Timeout: 6
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_AUDIT_TABLE: !Ref DynamoDBStackAuditTableName
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: CloudWatchLogGroup
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt CloudWatchLogGroup.Arn
              Effect: Allow
        - Version: 2012-10-17
          Statement:
            - Sid: DynamoDB
              Action:
                - dynamodb:BatchWriteItem
              Resource:
                - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBStackAuditTableName}
              Effect: Allow
      LoggingConfig:
        LogGroup: !Ref CloudWatchLogGroup
    Metadata:
      BuildMethod: makefile
