name: dev

concurrency:
  group: dev
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'stage'
        default: 'dev'
      account:
        type: choice
        description: 'account'
        default: 'dev'
        options:
          - dev
          - feature
      sha:
        description: 'commit sha'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  deploy:
    uses: 'starterstack/starterstack/.github/workflows/main.yml@main'
    secrets: 'inherit'
    with:
      account: ${{ github.event.inputs.account || 'dev' }}
      stage: ${{ github.event.inputs.stage || 'dev' }}
      sha: ${{ github.event.inputs.sha || github.sha }}
