name: sls-mentor

on:
  workflow_call:
    inputs:
      aws-regions:
        required: true
        type: string
    secrets:
      aws-ci-role:
        required: true

env:
  AWS_RETRY_MODE: standard
  AWS_MAX_ATTEMPTS: 6

jobs:
  sls-mentor-regions:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      regions: ${{ steps.regions.outputs.regions }}
    steps:
      - uses: actions/checkout@v4
      - id: regions
        run: |
          echo "regions=$(printf "${{ inputs.aws-regions }}" | \
            jq \
              -c \
              --raw-input \
              '''
                split(" ") |
                sort |
                unique |
                map({ region: . })
              ''')" >> $GITHUB_OUTPUT
  sls-mentor:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [sls-mentor-regions]
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.sls-mentor-regions.outputs.regions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.aws-ci-role }}
          aws-region: us-east-1
          role-duration-seconds: 900
      - name: run sls-mentor for ${{ matrix.region }}
        run: |
          npx \
            sls-mentor \
            --aws-region '${{ matrix.region }}' \
            --level 5
